image: registry.gitlab.com/redmic-project/docker/docker-deploy:latest

stages:
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

deploy-dev:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    STACK: etl
    SERVICES_TO_CHECK: etl_${CI_PROJECT_NAME}
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.dev.yml
    PUBLIC_PORT: ${DEV_PUBLIC_PORT}
    PASSIVE_PUBLIC_PORT: ${DEV_PASSIVE_PUBLIC_PORT}
    PUBLIC_HOST: ${PRO_PUBLIC_HOST}
  script:
    - create-nets.sh ingest-ftp-net
    - >
      deploy.sh COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_PORT=${PUBLIC_PORT}
      PASSIVE_PUBLIC_PORT=${PASSIVE_PUBLIC_PORT} PUBLIC_HOST=${PUBLIC_HOST}
  environment:
    name: dev
  only:
    - dev
  when: manual

deploy-supporting-branch:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    STACK: etl
    SERVICES_TO_CHECK: etl_${CI_PROJECT_NAME}
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.dev.yml
    PUBLIC_PORT: ${DEV_PUBLIC_PORT}
    PASSIVE_PUBLIC_PORT: ${DEV_PASSIVE_PUBLIC_PORT}
    PUBLIC_HOST: ${PRO_PUBLIC_HOST}
  script:
    - create-nets.sh ingest-ftp-net
    - >
      deploy.sh COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_PORT=${PUBLIC_PORT}
      PASSIVE_PUBLIC_PORT=${PASSIVE_PUBLIC_PORT} PUBLIC_HOST=${PUBLIC_HOST}
  environment:
    name: dev
  only:
    - branches
  except:
    - master
    - dev
  when: manual

deploy-pro:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    STACK: etl
    SERVICES_TO_CHECK: etl_${CI_PROJECT_NAME}
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.prod.yml
    PUBLIC_PORT: ${PRO_PUBLIC_PORT}
    PASSIVE_PUBLIC_PORT: ${PRO_PASSIVE_PUBLIC_PORT}
    PUBLIC_HOST: ${PRO_PUBLIC_HOST}
  script:
    - create-nets.sh ingest-ftp-net
    - >
      deploy.sh COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_PORT=${PUBLIC_PORT}
      PASSIVE_PUBLIC_PORT=${PASSIVE_PUBLIC_PORT} PUBLIC_HOST=${PUBLIC_HOST}
  environment:
    name: pro
  only:
    - master
  when: manual
