include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

variables:
  STACK: etl

.deploy:
  script:
    - >
      deploy.sh COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_PORT=${PUBLIC_PORT}
      PUBLIC_HOST=${PUBLIC_HOST}
