version: '3.5'

services:
  ingest-sftp:
    image: stilliard/pure-ftpd:hardened
    networks:
      - ingest-ftp-net
    ports:
      - target: 21
        protocol: tcp
        mode: ingress
      - target: 30000
        protocol: tcp
        mode: ingress
      - target: 30001
        protocol: tcp
        mode: ingress
      - target: 30002
        protocol: tcp
        mode: ingress
      - target: 30003
        protocol: tcp
        mode: ingress
      - target: 30004
        protocol: tcp
        mode: ingress
      - target: 30005
        protocol: tcp
        mode: ingress
      - target: 30006
        protocol: tcp
        mode: ingress
      - target: 30007
        protocol: tcp
        mode: ingress
      - target: 30008
        protocol: tcp
        mode: ingress
      - target: 30009
        protocol: tcp
        mode: ingress

    volumes:
      - ingest-data-vol:/data/ftp
      - ingest-ftp-ssl-vol:/etc/ssl/private
      - ingest-ftp-passwd-db-vol:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: ${PUBLICHOST}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          memory: 52M

networks:
  ingest-ftp-net:
    name: ${INGEST_FTP_NET_NAME:-ingest-ftp-net}
    attachable: true
