version: '3.5'

services:
  ingest-sftp:
    image: stilliard/pure-ftpd:hardened
    networks:
      - ingest-ftp-net
    ports:
      - target: 21
        published: ${PUBLIC_PORT}
        protocol: tcp
        mode: ingress
      - target: 30000-30009
        published: ${PASSIVE_PUBLIC_PORT}
        protocol: tcp
        mode: host
    volumes:
      - ingest-data-vol:/data/ftp
      - ingest-ftp-ssl-vol:/etc/ssl/private
      - ingest-ftp-passwd-db-vol:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: ${PUBLICHOST}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          memory: 52M

networks:
  ingest-ftp-net:
    external: true
